version: "3"
services:
    api:
        build: .
        # restart: always
        command: npm start
        volumes:
            - .:/usr/src/app/
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
        depends_on:
            - db
            - email
        environment:
            - NODE_ENV=production
            - MONGODBURL=mongodb://root:rootpassword@db
            - EMAILSERVICEBASEURL=http://email
    db:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=rootpassword
        # ports:
        #     - 27017:27017
        volumes:
            - mongodb_data_container:/data/db
    email:
        build: .
        # restart: always
        command: npm run start_email
        # expose:
        #     - "80"
        # ports:
        #     - 80:4000
        volumes:
            - .:/usr/src/app/
            - /usr/src/app/node_modules
        depends_on:
            - emaildb
        environment:
            - NODE_ENV=production
            - PORT=80
            - MONGODBURL=mongodb://root:rootpassword@emaildb
            - MAINSERVICEBASEURL='api.instadecoy.****'
    emaildb:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=rootpassword
        # ports:
        #     - 27018:27017
        volumes:
            - mongodb_data_container_email:/data/db
volumes:
    mongodb_data_container:
    mongodb_data_container_email:
